Nnoggie/MythicDungeonTools

- MethodDungeonTools.lua
Chose is the past tense, which makes no sense since the user is currently choosing
> Spell correction and capitalize NPC

- python/combatLogReader/CombatLogReader.py
Now checks all bosses one by one if first is not found.
> Fix for Blizzard boss name laziness

- python/combatLogReader/CombatLogReader.py
Any other dungeon since Legion:
Patch Dungeon - DUNGEONNAME - Challenge
One random Shadowlands dungeon:
9.0 Dungeon - Challenge - Theater of Pain
OK Blizzard.
> Fix for Blizzard changing count lookup naming convention

- MythicDungeonTools.lua
* Week 9 had inverted level 4/7 affixes
* Week 11 had wrong affix IDs
> Fixup affix list

- DungeonEnemies.lua
- EnemyInfo.lua
- MythicDungeonTools.lua
Hello, I am a user who enjoys Wow in Korea.
I think MTD is a great tool.
However, there are a few things to be desired, but in Korea, the name and creature type of monsters are often written in English, so it is often confusing.
So, I modified the code a little bit so that the name and creature type can be displayed by region, so please check it.
In addition, the notation of life is slightly different in Korea.
I don't know where to put this code.
I give you the notation of life in Korea as below, so I would appreciate it if you could consider adding a function that can be displayed differently by localization.
```lua
function MDT:FormatEnemyHealth(amount)
amount = tonumber(amount)
if not amount then return "" end
if amount < 1e3 then
return 0
elseif amount >= 1e16 then
return …
```
> Modified the code to display by local monster name and creature type

- Shadowlands/SanguineDepths.lua
Removed the group
Fix for issue #207
This tick can be pulled without pulling all the others
> Change Gluttonous Tick 2 group in Sanguine Depths

- DungeonEnemies.xml
possible solution for fix #254
will make circle around inspiring mobs bigger to still have it visible while mobs are marked for pull
> make inspiring better visible

- MythicDungeonTools.lua
With the button gone, it makes sense to disable this for anyone
unfortunate enough to still have it enabled.
> Force disable MDI mode

- Shadowlands/TazaveshLower.lua
- Shadowlands/TazaveshUpper.lua
- python/combatLogReader/CombatLogReader.py
Since mapping the dungeons they've changed the required enemy forces in Tazavesh Upper as reported by Laynz.
Tazavesh Lower and all mob count appears to remain the same.
Cleaned out a redundant, wrong and unused count from Tazavesh Lower. This changes nothing, but cleans the code.
A fix has also been added for the CombatLogReader that gave errors on some combatlogs.
> Fixing TazaveshUpper count as per patch 9.2.0.42423

- Shadowlands/TazaveshLower.lua
Tracker Zo'korss in Lower Tazavesh (Streets) has stealth detect.
> Added Steath detect for Tracker Zo'Korss in Lower Tazavesh

- Shadowlands/TazaveshLower.lua
- Shadowlands/TazaveshUpper.lua
Upper I believe is fully mapped, only right side of murloc room might have an inspired on that side
Lower is also fully mapped but then last room and right hand side corridor noone uses hasn't been checked
> Adding Inspired Mobs to Tazavesh Upper and Lower

- python/combatLogReader/update_dungeon_count.py
Handles mobs that give count through a gameevent rather than on kill.
Currently Shadow of Zul and Eye of Sethralis.
> Converter for count obtained by GameEvents

- Shadowlands/DeOtherSide.lua
Turns out the mob does give 2 count the id has changed to 170486
> npcid and count update for Atal'ai Devoted now with id 170486

- python/update_dungeon_count.py
The file format uses spaces, the update script did not take those into
account.
No data changes are currently observed from this fix
> Fix total dungeon enemy count replacement

- Dragonflight/TempleOfTheJadeSerpent.lua
Verifying TempleOfTheJadeSerpent.
- Total dungeon count has been updated: 289 -> 297
> update temple dungeon count

- Dragonflight/TempleOfTheJadeSerpent.lua
- python/dungeon_mapper.py
- Handle GameEvent for Shadowmoon Burial Grounds Carrion Worm
- Verifying Temple Of The Jade Serpent.
- Total dungeon count has been updated: 297 -> 410
> GameEvent and temple count update

- MythicDungeonTools.lua
Currently when you switch dungeons using the dropdown the old progress bar is shown from whatever you were last viewing.
> Update progress bar when switching dungeons

- python/update_dungeon_count.py
This fix solves the issue where the update_dungeon_count.py script breaks if lines end in , instead of ;.
The script now accepts either symbol to end a line.
> alter npc name pattern to account for both , and ;

- python/dungeon_mapper.py
- python/web_scraper.py
- fixes error trying to pull displayid from an outdated wow.tools api, by changing to wowhead
- fixes error when the boss npc id is contained in, but not equal to journalencounter boss name
> get displayID from wowhead instead of wow.tools

- MythicDungeonTools.lua
Remove the status bars from the Ace frames created, since they look out of place and even overlap other UI elements in some places.
Wasn't able to test the CustomColorFrame, because that errored out in an unrelated way.
Bit of a hack, would be better in a separate function, but the code I'm modifying is copied multiple times anyway, and if this would be split off it should be split off in a function that does more than just that, ie set title, size and layout, disables resizes etc. Maybe sth for a follow-up patch?
> Remove the statusbg element from all of the Ace frames created

- MythicDungeonTools.lua
I noticed whenever you delete a pull the count wont get updated until you hover a different pull or add/remove count. 
So i made DeletePull call UpdateProgressbar.
> Update progress bar when deleting pulls

- TheWarWithin/TheRookery.lua
Coalescing Void Diffusers can detect stealth. High-level groups often execute a popular skip that involves going invisible and hugging the wall to stay out of detection range. Low- to mid-level PUGs that try to mimic this pull—after seeing experienced groups do it—often fail because they don't realize the mobs can detect stealth.
> Add stealthdetect to Coalescing Void Diffusers in Rookery
