Nnoggie/MythicDungeonTools

- MethodDungeonTools.lua
Cleaned up FormatEnemyHealth function code.
> Better FormatEnemyHealth Code

- BattleForAzeroth/TolDagor.lua
Added the alliance version of the prisioners in the cells.
> TolDagor Alliance Prisioners Buffs 

- AceGUIWidget-MethodDungeonToolsPullButton.lua
- MethodDungeonTools.lua
- Insert before
- Insert after
- Merge up
- Merge down
> - Implemented all requested features of Issue #66

- DungeonEnemies.lua
Hey Nnogga,
I know you've been looking at this so I figured I'd take a shot. Very much work in progress.
Looks like this right now:
There is some code to make the polygon larger but that seems to somewhat mess up the smoothing.
> WIP: show convex hull around selected pull

- DungeonEnemies.lua
- MethodDungeonTools.lua
> Hide and don't count beguiling mobs for keys < 10

- python/get_count.py
The Spark Channeler in Temple has multiple CriteriaTree rows that
all apply simultaneously once you kill it. Add a pass that combines
all rules into one count value for one NPC ID.
> sum count granted for NPCs

- AceGUIWidget-MethodDungeonToolsPullButton.lua
- DungeonEnemies.lua
- MethodDungeonTools.lua
> Automatically color new pulls

- MethodDungeonTools.lua
- toolbar.lua
-Added multiple premade color palletes
-Added functionality for user to make custom color palette
-Fixed a few bugs with automatic coloring functionality itself
-Added choice to automatically color preset on import (currently no way to toggle this off - will be fixed)
-Do not merge toolbar.lua
> Added functionality to automatic coloring

- python/combatLogReader/CombatLogReader.py
- Added how to use guide
- Added filtering for player pets
- Added functionality to easily "aura-map"
- Added "aura-mapping" of Inspiring Presence
- Added export of total dungeon count
- Added export of enUS locale translation of npc names
- Added proper support for sublevels
- No additional shady changes to other files
> Updates to CombatLogReader

- python/combatLogReader/CombatLogReader.py
- Now handles mobs with the same name, but different npcID ensuring always accurate count
- Changed locale_en output in line with changes to MDT (no L[...] brackets for creatureType and name
- Filtering of enemy pets with low HP (currently <20k) and no count
- Protection against NPCs without a name on first hit in the combat log
- Minor readability improvements and changed to always output locale_en with unique names
> Improvements for automatic mapping

- DungeonEnemies.xml
Reverts Nnoggie/MythicDungeonTools#255
> Revert "make inspiring better visible"

- DungeonEnemies.lua
- Shadowlands/DeOtherSide.lua
- Shadowlands/HallsOfAtonement.lua
- Shadowlands/MistsOfTirnaScithe.lua
- Shadowlands/Plaguefall.lua
- Shadowlands/SanguineDepths.lua
- Shadowlands/SpiresOfAscension.lua
- Shadowlands/TheNecroticWake.lua
- Shadowlands/TheaterOfPain.lua
New lieutenants positions for week 3
> Add tormented rotation (all weeks). New positions for NW and SD

- python/combatLogReader/CombatLogReader.py
Forcing Tazavesh Streets ID if a certain boss is present
> CombatLogReader fix for Tazavesh

- Shadowlands/TazaveshLower.lua
Added missing abilities as reported in #278.
> Added missing abilities for 3 trash mobs in Lower Tazavesh

- MythicDungeonTools.lua
I tried to find a way to not rely on the hardcoded table but not knowing which week it is is kinda annoying.
> Update Affix Data for S3

- python/combatLogReader/update_dungeon_count.py
Adds npc name and expansion header to print
> Add npc name and expansion header to print

- MythicDungeonTools.lua
Updates and stores affix weeks locally to populate the AffixWeeks table.
> Local affix rotation handling with UpdateAffixWeek

- MythicDungeonTools.lua
Don't update AffixWeeks if season start time is in the future
> Fix Local affix rotation around season start

- python/dungeon_mapper.py
- python/update_dungeon_count.py
Replaces convoluted gameevent function with more streamlined approach
Adds support for shrouded affix demons
> Streamlined game event trigger handling

- python/dungeon_mapper.py
- python/update_dungeon_count.py
- python/web_scraper.py
- Hardcoded Abstract Nullifier into update_dungeon_counter and implemented warning if its count ever changes
- Auto-changes working directory to /python before running scripts
- Adopted two spaces instead of tabs for mapping output
- Improved mapping progress bar
> Upper Karazhan hardcoded and mapping progressbar

- CHANGELOG.txt
- MythicDungeonTools.toc
- Shadowlands/TazaveshLower.lua
- Tazavesh Streets: Added missing Infiltrator
> Mapping updates

- python/dungeon_mapper.py
New: The user can pick which combatlog they wanna map
Fix: Hardcoded Shadowmoon Burial Ground name outlier
> file picker + shadowmoon burial fix

- python/update_dungeon_count.py
Includes:
- Fix for Shadowmoon Burial Ground (Hardcoded)
- Formatting changes
> Fix for Shadowmoon Burial Grounds

- python/dungeon_mapper.py
- python/update_dungeon_count.py
Includes:
- Formatting dungeon_mapper.py
- Generalized fix for old dungeons with non-conforming namestyle
> Dragonflight dev

- python/update_dungeon_count.py
- python/web_scraper.py
commented out code that tries to download files from wowtools
> comment out download code

- Locales/enUS.lua
- Modules/ErrorHandling.lua
- Modules/load_modules.xml
- MythicDungeonTools.lua
Handle most mdt errors internally and provide an easy way for users to report these errors.
> Error handling

- python/dungeon_mapper.py
Add option to map with new style (combined map, NPC's mapped in rows)
> Stinth season3

- python/web_scraper.py
Get displayid from ptr2.wowhead.com instead of retail
> get displayid from ptr2

- Dragonflight/DawnOfTheInfiniteLower.lua
> DOTI Lower: Stealth detection on Infinite Infiltrator (#547 / #548)

- BattleForAzeroth/SiegeofBoralus.lua
- Modules/DungeonSelect.lua
- Modules/EnemyInfo.lua
- Modules/Toolbar.lua
- MythicDungeonTools.lua
Use SetTopLevel to have better interaction with other addons and frames open at the same.
https://warcraft.wiki.gg/wiki/API_Frame_SetToplevel
For this to work properly some modifications have to be made to child frames.
> main_frame SetTopLevel

- Modules/Transmission.lua
This fixes a user linking multiple routes in chat but only the latest one bein imported
> Fix transmission to support multiple routes per player

- Locales/enUS.lua
- Modules/Pointsofinterest.lua
- TheWarWithin/TheRookery.lua
Update The Rookery item (located at the first boss position).
The enUS localization descriptions for the items need to be completed 
(the approximate meaning has already been written in the code comments).
> Update The Rookery Item

- TheWarWithin/DarkflameCleft.lua
> fix: creeping shadows 469620 is now a magic debuff
